// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replaces a provider key in the running server only; null restores environment lookup.
 */
export type ProviderCredentialsSetParams = { provider: string, apiKey: string | null, };
