// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Each field is `null` when the thread's model receives nothing from that source.
 */
export type ThreadElpisInstructionsReadResponse = {
/**
 * The thread's configured `developer_instructions`.
 */
developerInstructions: string | null,
/**
 * The global and project AGENTS.md text the Context Ledger admits.
 */
agentsMd: string | null,
/**
 * The admitted continuity section: MEMORY.md, development rules, GOAL.md, ES.md and
 * files added with `/add`.
 */
continuity: string | null, };
