// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSmartPruneAdmissionSnapshot } from "./ThreadSmartPruneAdmissionSnapshot";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadSmartPruneSnapshot = { enabled: boolean, examinedOutputs: number, admittedOutputs: number, unchangedOutputs: number, failedBatches: number, approxSourceTokens: number, approxAdmittedTokens: number, approxSavedTokens: number, optimizerRequests: number, optimizerUsageReports: number, optimizerUsage: TokenUsageBreakdown, optimizerLatencyMs: number, mainRequestSequence: number, latest?: ThreadSmartPruneAdmissionSnapshot, };
