// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSmartPruneSnapshot } from "./ThreadSmartPruneSnapshot";

/**
 * Thread-scoped Smart Prune state, sent after each token-usage update, after a config
 * refresh changes the switch, and when a client attaches to a thread.
 *
 * This is intentionally separate from token usage because a config change can
 * happen without an active turn or a provider usage sample.
 */
export type ThreadSmartPruneUpdatedNotification = { threadId: string, smartPrune: ThreadSmartPruneSnapshot, };
