// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reads the Elpis instruction text a thread's next model request carries, so a client that
 * runs the thread's turns on another engine can give that model the same instructions.
 */
export type ThreadElpisInstructionsReadParams = { threadId: string, };
