// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextAttribution } from "./ThreadContextAttribution";
import type { ThreadSmartPruneSnapshot } from "./ThreadSmartPruneSnapshot";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null, contextPruneSavedTokens: number, smartPrune: ThreadSmartPruneSnapshot, contextAttribution?: ThreadContextAttribution, };
