// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estimated composition of the exact request built for the latest provider attempt.
 * Values are never padded to reconcile with provider token accounting.
 */
export type ThreadContextAttribution = { systemInstructions: number, developerMessages: number, userMessages: number, agentMessages: number, reasoning: number, toolCalls: number, toolResults: number, toolDefinitions: number, outputSchema: number, unrecognizedItems: number, estimatedTotal: number, };
