// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadSmartPruneAdmissionSnapshot = { admissionId: string, auditPath: string, examinedOutputs: number, admittedOutputs: number, approxSourceTokens: number, approxAdmittedTokens: number, approxSavedTokens: number, requestSequence?: number | null, requestInputSha256?: string, requestLinkageVerified: boolean, responseId?: string, responseUsage?: TokenUsageBreakdown, responseLinkageVerified: boolean, };
