// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsageBreakdown = { totalTokens: number, inputTokens: number, cachedInputTokens: number,
/**
 * Input tokens written to the prompt cache by this request.
 *
 * `None` means the provider did not report the field, which is not the same as a reported
 * zero.
 */
cacheWriteTokens?: number | null, outputTokens: number, reasoningOutputTokens: number, };
