// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnActivityStatus } from "./TurnActivityStatus";

export type TurnActivityUpdatedNotification = { threadId: string, turnId: string, status: TurnActivityStatus, durationMs: number | null, timeToFirstTokenMs: number | null, };
