// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkGraphTaskSummary } from "./WorkGraphTaskSummary";

export type WorkGraphSummary = { id: string, name: string, status: string, maxConcurrency: number, error: string | null, tasks: Array<WorkGraphTaskSummary>, eventCount: number, };
