// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type WorkGraphTaskSummary = { id: string, kind: string, title: string, status: string, dependencies: Array<string>, assignedThreadId: string | null, result: JsonValue | null, evidence: Array<string>, failureReason: string | null, };
