// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scalar timing facts only; no messages, paths, account, provider, or trace data.
 */
export type TurnProfileSummary = { beforeFirstSamplingMs: bigint, samplingMs: bigint, compactionMs: bigint, betweenSamplingOverheadMs: bigint, toolBlockingMs: bigint, afterLastSamplingMs: bigint, samplingRequestCount: bigint, samplingRetryCount: bigint, };
