// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnActivityStatus } from "./TurnActivityStatus";
import type { TurnProfileSummary } from "./TurnProfileSummary";

/**
 * Ephemeral scalar-only terminal activity; never part of a persisted turn.
 */
export type TurnActivityUpdatedNotification = { threadId: string, turnId: string, status: TurnActivityStatus, startedAt: number | null, durationMs: number | null, timeToFirstTokenMs: number | null, profile: TurnProfileSummary | null, };
