// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnCostAvailability } from "./TurnCostAvailability";

export type TurnCostState = { "type": "unavailable", reason: TurnCostAvailability, } | { "type": "priced", backendTotalUsd: string, };
